{{- $platform := index .Values "platform" | default dict }}
{{- $certManager := index $platform "certManager" | default dict }}
{{- $issuerRef := index $certManager "issuerRef" | default dict }}
{{- range .Values.ingresses }}
{{- if and .tls (eq .tls.mode "cert-manager") }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-%s" $.Values.metadata.name .name | quote }}
  namespace: {{ $.Values.metadata.namespace | quote }}
spec:
  secretName: {{ printf "%s-%s-tls" $.Values.metadata.name .name | quote }}
  dnsNames:
  {{- range .rules }}
    - {{ .host | quote }}
  {{- end }}
  issuerRef:
    name: {{ index $issuerRef "name" | quote }}
    kind: {{ index $issuerRef "kind" | quote }}
{{- end }}
{{- end }}
