{{- if .Values.database }}
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ printf "%s-db" .Values.metadata.name | quote }}
  namespace: database-system
spec:
  name: {{ .Values.database.name | quote }}
  owner: {{ .Values.database.owner | default "defaultuser" | quote }}
  cluster:
    name: shared-db
{{- end }}
