{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $.Values.metadata.name .name | quote }}
  namespace: {{ $.Values.metadata.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ $.Values.metadata.name | quote }}
spec:
  selector:
    app.kubernetes.io/name: {{ $.Values.metadata.name | quote }}
  ports:
  {{- range .ports }}
    - name: {{ .name | quote }}
      port: {{ .port }}
      targetPort: {{ .targetPort | quote }}
  {{- end }}
{{- end }}
